/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burgertime;

import Console.Console;
import Environnement.Plateau;
import Joueur.Joueur;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author 
 */
public class BurgerTime extends javax.swing.JFrame {

    public static Plateau pl;
    public static Joueur j;
    public static Console console;
    
    public BurgerTime() {
        pl=new Plateau();
        j=new Joueur();
        console=new Console();
        
        initComponents();
        
        this.setBackground(new Color(11,22,22));
        this.add(console);
        console.requestFocus();
        centrer();        
    }

        private void centrer()
    {
        Dimension s = Toolkit.getDefaultToolkit().getScreenSize();        
        int x=(int)(s.getWidth()-this.getWidth())/2;
        int y=(int)(s.getHeight()-this.getHeight())/2;
        this.setLocation(x,y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BQuitter = new javax.swing.JButton();
        BJouer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(11, 22, 22));
        setMinimumSize(new java.awt.Dimension(720, 650));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(11, 22, 22));

        BQuitter.setBackground(new java.awt.Color(0, 0, 0));
        BQuitter.setForeground(new java.awt.Color(255, 255, 255));
        BQuitter.setText("Quitter");
        BQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQuitterActionPerformed(evt);
            }
        });
        jPanel1.add(BQuitter);

        BJouer.setBackground(new java.awt.Color(0, 0, 0));
        BJouer.setForeground(new java.awt.Color(255, 255, 255));
        BJouer.setText("Jouer");
        BJouer.setFocusable(false);
        BJouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJouerActionPerformed(evt);
            }
        });
        jPanel1.add(BJouer);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQuitterActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_BQuitterActionPerformed

    private void BJouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BJouerActionPerformed
        // TODO add your handling code 
        pl.nouvellePartie();
    }//GEN-LAST:event_BJouerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurgerTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurgerTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurgerTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurgerTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BurgerTime partie=new BurgerTime();
                partie.setVisible(true);
                Thread th=new Thread(new Runnable()
                {
                    public void run()
                    {
                        while(true)
                        {
                            partie.repaint();
                            try
                            {
                                Thread.currentThread().sleep(1000);
                            }
                            catch(InterruptedException e)
                            {
                                e.printStackTrace();
                            }
                        }
                    }
                });
                th.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BJouer;
    private javax.swing.JButton BQuitter;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
